# Pandas

Pandas is a Python library for data analyses and manipulation. It works with tabular data (like Excel, or CSV files).

This is one of the packages we installed in our environment that doesn't come with base Python.

In [1]:
import pandas as pd

Pandas has `read` functions for a few different file formats.

In [ ]:
df = pd.read_csv('../../05_src/data/slides_data/bicycle_thefts_4326.csv')

In [4]:
# if this didn't work, check where you are with os
import os
os.getcwd()

'c:\\Users\\Madeleine\\Documents\\DSI_course\\python\\04_this_cohort\\live-code'

In [5]:
type(df)

pandas.DataFrame

In [ ]:
df.head(3)

In [8]:
df.shape

(25569, 33)

In [ ]:
df = pd.read_csv('../../05_src/data/slides_data/bicycle_thefts_4326.csv')

In [ ]:
df.dtypes # show the data types of the columns in the data

_id                        int64
OBJECTID                   int64
event_unique_id              str
Primary_Offence              str
Occurrence_Date              str
Occurrence_Year            int64
Occurrence_Month             str
Occurrence_DayOfWeek         str
Occurrence_DayOfMonth      int64
Occurrence_DayOfYear       int64
Occurrence_Hour            int64
Report_Date                  str
Report_Year                int64
Report_Month                 str
Report_DayOfWeek             str
Report_DayOfMonth          int64
Report_DayOfYear           int64
Report_Hour                int64
Division                     str
City                         str
Hood_ID                      str
NeighbourhoodName            str
Location_Type                str
Premises_Type                str
Bike_Make                    str
Bike_Model                   str
Bike_Type                    str
Bike_Speed                 int64
Bike_Colour                  str
Cost_of_Bike             float64
Status                       str
ObjectId2                  int64
geometry                     str
dtype: object

In [ ]:
df.tail(2) # show the last 2 rows

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [12]:
df; # just running df will show the first 5 and last 5 rows

In [15]:
# we can rename columns
# this takes a dictionary of column names
df = df.rename(columns = {"cost_of_bike":"bike_cost"})

In [ ]:
# convert all columns to lowercase
df.columns = df.columns.str.lower()

In [23]:
df["geometry"];

In [21]:
df.columns

Index(['_id', 'objectid', 'event_unique_id', 'primary_offence',
       'occurrence_date', 'occurrence_year', 'occurrence_month',
       'occurrence_dayofweek', 'occurrence_dayofmonth', 'occurrence_dayofyear',
       'occurrence_hour', 'report_date', 'report_year', 'report_month',
       'report_dayofweek', 'report_dayofmonth', 'report_dayofyear',
       'report_hour', 'division', 'city', 'hood_id', 'neighbourhoodname',
       'location_type', 'premises_type', 'bike_make', 'bike_model',
       'bike_type', 'bike_speed', 'bike_colour', 'cost_of_bike', 'status',
       'objectid2', 'geometry'],
      dtype='str')

Aside: this dataframe has a 'geometry' column, which means it is likely a spatial dataset. The package `geopandas` can be used to work with and map spatial data.

E.g.

```
import geopandas as gpd
gdf = gpd.read_file("file_path")
gdf.plot() # plots all the data on a map!
```

In [25]:
# select columns with square brackets
df["status"].unique()

<StringArray>
['STOLEN', 'RECOVERED', 'UNKNOWN']
Length: 3, dtype: str

In [26]:
df["status"].value_counts()

status
STOLEN       24807
UNKNOWN        454
RECOVERED      308
Name: count, dtype: int64

In [ ]:
# there are no NAs in the status column
df.loc[df["status"].isna()]

Empty DataFrame
Columns: [_id, objectid, event_unique_id, primary_offence, occurrence_date, occurrence_year, occurrence_month, occurrence_dayofweek, occurrence_dayofmonth, occurrence_dayofyear, occurrence_hour, report_date, report_year, report_month, report_dayofweek, report_dayofmonth, report_dayofyear, report_hour, division, city, hood_id, neighbourhoodname, location_type, premises_type, bike_make, bike_model, bike_type, bike_speed, bike_colour, cost_of_bike, status, objectid2, geometry]
Index: []

[0 rows x 33 columns]

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   objectid               25569 non-null  int64
 2   event_unique_id        25569 non-null  str
 3   primary_offence        25569 non-null  str
 4   occurrence_date        25569 non-null  str
 5   occurrence_year        25569 non-null  int64
 6   occurrence_month       25569 non-null  str
 7   occurrence_dayofweek   25569 non-null  str
 8   occurrence_dayofmonth  25569 non-null  int64
 9   occurrence_dayofyear   25569 non-null  int64
 10  occurrence_hour        25569 non-null  int64
 11  report_date            25569 non-null  str
 12  report_year            25569 non-null  int64
 13  report_month           25569 non-null  str
 14  report_dayofweek       25569 non-null  str
 15  report_dayofmonth      25569 non-null  int64
 16  report_dayofyear       25569 non-null  int64
 17  report_hour            25569 non-null  int64
 18  division               25569 non-null  str
 19  city                   25569 non-null  str
 20  hood_id                25569 non-null  str
 21  neighbourhoodname      25569 non-null  str
 22  location_type          25569 non-null  str
 23  premises_type          25569 non-null  str
 24  bike_make              25448 non-null  str
 25  bike_model             15923 non-null  str
 26  bike_type              25569 non-null  str
 27  bike_speed             25569 non-null  int64
 28  bike_colour            23508 non-null  str
 29  cost_of_bike           23825 non-null  float64
 30  status                 25569 non-null  str
 31  objectid2              25569 non-null  int64
 32  geometry               25569 non-null  str
dtypes: float64(1), int64(12), str(20)
memory usage: 6.4 MB

In pandas, most operations return a new
DataFrame by default and do not modify
the original DataFrame in place unless you
explicitly tell them to.

In [ ]:
df = df.drop(columns = "_id") # drop the _id column

In [33]:
# make a new column
df["current_year"] = 2026

In [37]:
df["occurrence_month"] = df["occurrence_month"].str[:3]

In [38]:
df.head()

,objectid,event_unique_id,primary_offence,occurrence_date,occurrence_year,occurrence_month,occurrence_dayofweek,occurrence_dayofmonth,occurrence_dayofyear,occurrence_hour,...,bike_make,bike_model,bike_type,bike_speed,bike_colour,cost_of_bike,status,objectid2,geometry,current_year
0,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,Oct,Tuesday,3,276,14,...,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,Nov,Wednesday,8,312,3,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,Sep,Friday,14,257,9,...,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
3,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,18,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,12,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026

## Filtering and selecting data

You can filter data by passing a series of true / false to use as indices. 
You can also use .loc to select by index explicitly

In [ ]:
df.loc[~df["bike_model"].isna()].head() # select only rows where bike_model is not NaN

,objectid,event_unique_id,primary_offence,occurrence_date,occurrence_year,occurrence_month,occurrence_dayofweek,occurrence_dayofmonth,occurrence_dayofyear,occurrence_hour,...,bike_make,bike_model,bike_type,bike_speed,bike_colour,cost_of_bike,status,objectid2,geometry,current_year
0,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,Oct,Tuesday,3,276,14,...,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,Sep,Friday,14,257,9,...,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
5,18003,GO-20151861057,THEFT UNDER,2015-09-01T00:00:00,2015,Sep,Tuesday,1,244,0,...,OTHER,UNK,RC,18,TRQ,100.0,STOLEN,6,"{'type': 'Point', 'coordinates': (-79.51960669...",2026
6,18013,GO-20169001537,THEFT UNDER,2016-02-18T00:00:00,2016,Feb,Thursday,18,49,9,...,NO,SASQUATCH,MT,18,WHI,0.0,STOLEN,7,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
9,21999,GO-20149003203,THEFT UNDER,2014-05-07T00:00:00,2014,May,Wednesday,7,127,18,...,UK,HARDROCK,MT,24,ONG,550.0,STOLEN,10,"{'type': 'Point', 'coordinates': (-79.51132657...",2026

## Grouping

In [46]:
df.groupby("occurrence_dayofweek")['cost_of_bike'].mean()

occurrence_dayofweek
Friday       952.799510
Monday       908.837284
Saturday     967.881717
Sunday       977.036629
Thursday     913.643642
Tuesday      978.617493
Wednesday    951.643933
Name: cost_of_bike, dtype: float64

In [53]:
df.columns

Index(['objectid', 'event_unique_id', 'primary_offence', 'occurrence_date',
       'occurrence_year', 'occurrence_month', 'occurrence_dayofweek',
       'occurrence_dayofmonth', 'occurrence_dayofyear', 'occurrence_hour',
       'report_date', 'report_year', 'report_month', 'report_dayofweek',
       'report_dayofmonth', 'report_dayofyear', 'report_hour', 'division',
       'city', 'hood_id', 'neighbourhoodname', 'location_type',
       'premises_type', 'bike_make', 'bike_model', 'bike_type', 'bike_speed',
       'bike_colour', 'cost_of_bike', 'status', 'objectid2', 'geometry',
       'current_year'],
      dtype='str')

In [55]:
mean_costs_by_date = df.groupby(["occurrence_month", 
                                 "occurrence_dayofweek"])[['cost_of_bike', 'bike_speed']].mean().reset_index()

In [56]:
mean_costs_by_date.sort_values(by = 'cost_of_bike')

   occurrence_month occurrence_dayofweek  cost_of_bike  bike_speed
36              Jul               Monday    741.718310   14.103110
10              Aug               Sunday    789.532258   14.770386
8               Aug               Monday    798.732510   14.325800
43              Jun               Monday    809.222222   13.766038
11              Aug             Thursday    816.303213   14.032197
..              ...                  ...           ...         ...
30              Jan             Saturday   1302.135135   12.687500
19              Dec              Tuesday   1367.057851   14.171642
1               Apr               Monday   1614.864865   12.476596
34              Jan            Wednesday   1955.522727   13.770833
17              Dec               Sunday   2027.781818   14.382114

[84 rows x 4 columns]

groupby is very powerful! We have only scratched the surface. You're doing SQL next. Know that all the operations you can do in SQL - grouping, aggregating, joining data, etc. - you can do this with pandas as well.

## Saving to file

In [52]:
mean_costs_by_date.to_csv("bike_avg_cost_by_date.csv", index = None)